# Global paths
data_root: /dtu-compute/msaca/sliceA_xray_pc
results_root: /dtu-compute/msaca/sliceA_xray_pc/results
scratch_root: /dtu-compute/msaca/sliceA_xray_pc/cache/preprocessing_run_002

# Session info
session_name: fbp_02
gpu_size: 16

wavelength: 70   # In KeV. (This variable is not used)
pixel_size: 3  # In microns


# Which datasets to preprocess
folders_to_preprocess: [1,2,]   # list of folder numbers
stride: 10                          # skip every n-th file

# Cropping parameters
crop:
  start_z: 620
  end_z: 1410
  start_x: 300
  end_x: 2048

# Projection angles
angles:
  start: 0
  end: 360
  n_projections: 6000

paganin:
  alpha: 0.2
  pad: 100

axis_placement: 248 

# File naming patterns
# ### = folder number (padded to 3 digits)
# #### = projection number (padded to 4 digits)
filenames:
  projection: "HA900_3um_mars_rock_###_/HA900_3um_mars_rock_###_####.edf"
  flat:       "HA900_3um_mars_rock_###_/refHST6000.edf"
  dark:       "HA900_3um_mars_rock_###_/dark.edf"   #dark.edf and darkend0000.edf

reconstruction:
  geometry:
    voxel_num_x: 3000
    voxel_num_y: 750
    initial_angle: 270
    angles:
      start: 0
      end: 180


stitching:
  start_indices:  [300, 94, 94, 94, 94, 94, 94,]
  end_indices: [693, 694, 694, 694, 694, 694, 788]
  overlap_pixels: 1